// This file is generated by scripts/extract-enums.js
// Do not edit manually.

export const BlockComponentTypes = {
    FluidContainer: 'minecraft:fluid_container',
    Inventory: 'minecraft:inventory',
    Piston: 'minecraft:piston',
    RecordPlayer: 'minecraft:record_player',
    Sign: 'minecraft:sign',
} as const;

export const BlockPistonState = {
    Expanded: 'Expanded',
    Expanding: 'Expanding',
    Retracted: 'Retracted',
    Retracting: 'Retracting',
} as const;

export const BlockVolumeIntersection = {
    Disjoint: 0,
    Contains: 1,
    Intersects: 2,
} as const;

export const ButtonState = {
    Pressed: 'Pressed',
    Released: 'Released',
} as const;

export const CustomComponentNameErrorReason = {
    NoNamespace: 1,
    DisallowedNamespace: 2,
} as const;

export const Difficulty = {
    Easy: 'Easy',
    Hard: 'Hard',
    Normal: 'Normal',
    Peaceful: 'Peaceful',
} as const;

export const Direction = {
    Down: 'Down',
    East: 'East',
    North: 'North',
    South: 'South',
    Up: 'Up',
    West: 'West',
} as const;

export const DisplaySlotId = {
    BelowName: 'BelowName',
    List: 'List',
    Sidebar: 'Sidebar',
} as const;

export const DyeColor = {
    Black: 'Black',
    Blue: 'Blue',
    Brown: 'Brown',
    Cyan: 'Cyan',
    Gray: 'Gray',
    Green: 'Green',
    LightBlue: 'LightBlue',
    Lime: 'Lime',
    Magenta: 'Magenta',
    Orange: 'Orange',
    Pink: 'Pink',
    Purple: 'Purple',
    Red: 'Red',
    Silver: 'Silver',
    White: 'White',
    Yellow: 'Yellow',
} as const;

export const EasingType = {
    InBack: 'InBack',
    InBounce: 'InBounce',
    InCirc: 'InCirc',
    InCubic: 'InCubic',
    InElastic: 'InElastic',
    InExpo: 'InExpo',
    InOutBack: 'InOutBack',
    InOutBounce: 'InOutBounce',
    InOutCirc: 'InOutCirc',
    InOutCubic: 'InOutCubic',
    InOutElastic: 'InOutElastic',
    InOutExpo: 'InOutExpo',
    InOutQuad: 'InOutQuad',
    InOutQuart: 'InOutQuart',
    InOutQuint: 'InOutQuint',
    InOutSine: 'InOutSine',
    InQuad: 'InQuad',
    InQuart: 'InQuart',
    InQuint: 'InQuint',
    InSine: 'InSine',
    Linear: 'Linear',
    OutBack: 'OutBack',
    OutBounce: 'OutBounce',
    OutCirc: 'OutCirc',
    OutCubic: 'OutCubic',
    OutElastic: 'OutElastic',
    OutExpo: 'OutExpo',
    OutQuad: 'OutQuad',
    OutQuart: 'OutQuart',
    OutQuint: 'OutQuint',
    OutSine: 'OutSine',
    Spring: 'Spring',
} as const;

export const EnchantmentSlot = {
    ArmorFeet: 'ArmorFeet',
    ArmorHead: 'ArmorHead',
    ArmorLegs: 'ArmorLegs',
    ArmorTorso: 'ArmorTorso',
    Axe: 'Axe',
    Bow: 'Bow',
    CarrotStick: 'CarrotStick',
    CosmeticHead: 'CosmeticHead',
    Crossbow: 'Crossbow',
    Elytra: 'Elytra',
    FishingRod: 'FishingRod',
    Flintsteel: 'Flintsteel',
    Hoe: 'Hoe',
    Pickaxe: 'Pickaxe',
    Shears: 'Shears',
    Shield: 'Shield',
    Shovel: 'Shovel',
    Spear: 'Spear',
    Sword: 'Sword',
} as const;

export const EntityComponentTypes = {
    AddRider: 'minecraft:addrider',
    Ageable: 'minecraft:ageable',
    Breathable: 'minecraft:breathable',
    CanClimb: 'minecraft:can_climb',
    CanFly: 'minecraft:can_fly',
    CanPowerJump: 'minecraft:can_power_jump',
    Color: 'minecraft:color',
    Color2: 'minecraft:color2',
    CursorInventory: 'minecraft:cursor_inventory',
    Equippable: 'minecraft:equippable',
    FireImmune: 'minecraft:fire_immune',
    FloatsInLiquid: 'minecraft:floats_in_liquid',
    FlyingSpeed: 'minecraft:flying_speed',
    FrictionModifier: 'minecraft:friction_modifier',
    Healable: 'minecraft:healable',
    Health: 'minecraft:health',
    Inventory: 'minecraft:inventory',
    IsBaby: 'minecraft:is_baby',
    IsCharged: 'minecraft:is_charged',
    IsChested: 'minecraft:is_chested',
    IsDyeable: 'minecraft:is_dyeable',
    IsHiddenWhenInvisible: 'minecraft:is_hidden_when_invisible',
    IsIgnited: 'minecraft:is_ignited',
    IsIllagerCaptain: 'minecraft:is_illager_captain',
    IsSaddled: 'minecraft:is_saddled',
    IsShaking: 'minecraft:is_shaking',
    IsSheared: 'minecraft:is_sheared',
    IsStackable: 'minecraft:is_stackable',
    IsStunned: 'minecraft:is_stunned',
    IsTamed: 'minecraft:is_tamed',
    Item: 'minecraft:item',
    LavaMovement: 'minecraft:lava_movement',
    Leashable: 'minecraft:leashable',
    MarkVariant: 'minecraft:mark_variant',
    Movement: 'minecraft:movement',
    MovementAmphibious: 'minecraft:movement.amphibious',
    MovementBasic: 'minecraft:movement.basic',
    MovementFly: 'minecraft:movement.fly',
    MovementGeneric: 'minecraft:movement.generic',
    MovementGlide: 'minecraft:movement.glide',
    MovementHover: 'minecraft:movement.hover',
    MovementJump: 'minecraft:movement.jump',
    MovementSkip: 'minecraft:movement.skip',
    MovementSway: 'minecraft:movement.sway',
    NavigationClimb: 'minecraft:navigation.climb',
    NavigationFloat: 'minecraft:navigation.float',
    NavigationFly: 'minecraft:navigation.fly',
    NavigationGeneric: 'minecraft:navigation.generic',
    NavigationHover: 'minecraft:navigation.hover',
    NavigationWalk: 'minecraft:navigation.walk',
    OnFire: 'minecraft:onfire',
    Projectile: 'minecraft:projectile',
    PushThrough: 'minecraft:push_through',
    Rideable: 'minecraft:rideable',
    Riding: 'minecraft:riding',
    Scale: 'minecraft:scale',
    SkinId: 'minecraft:skin_id',
    Strength: 'minecraft:strength',
    Tameable: 'minecraft:tameable',
    TameMount: 'minecraft:tamemount',
    TypeFamily: 'minecraft:type_family',
    UnderwaterMovement: 'minecraft:underwater_movement',
    Variant: 'minecraft:variant',
    WantsJockey: 'minecraft:wants_jockey',
} as const;

export const EntityDamageCause = {
    anvil: 'anvil',
    blockExplosion: 'blockExplosion',
    campfire: 'campfire',
    charging: 'charging',
    contact: 'contact',
    drowning: 'drowning',
    entityAttack: 'entityAttack',
    entityExplosion: 'entityExplosion',
    fall: 'fall',
    fallingBlock: 'fallingBlock',
    fire: 'fire',
    fireTick: 'fireTick',
    fireworks: 'fireworks',
    flyIntoWall: 'flyIntoWall',
    freezing: 'freezing',
    lava: 'lava',
    lightning: 'lightning',
    maceSmash: 'maceSmash',
    magic: 'magic',
    magma: 'magma',
    none: 'none',
    override: 'override',
    piston: 'piston',
    projectile: 'projectile',
    ramAttack: 'ramAttack',
    selfDestruct: 'selfDestruct',
    sonicBoom: 'sonicBoom',
    soulCampfire: 'soulCampfire',
    stalactite: 'stalactite',
    stalagmite: 'stalagmite',
    starve: 'starve',
    suffocation: 'suffocation',
    temperature: 'temperature',
    thorns: 'thorns',
    'void': 'void',
    wither: 'wither',
} as const;

export const EntityInitializationCause = {
    Born: 'Born',
    Event: 'Event',
    Loaded: 'Loaded',
    Spawned: 'Spawned',
    Transformed: 'Transformed',
} as const;

export const EquipmentSlot = {
    Chest: 'Chest',
    Feet: 'Feet',
    Head: 'Head',
    Legs: 'Legs',
    Mainhand: 'Mainhand',
    Offhand: 'Offhand',
} as const;

export const FluidType = {
    Lava: 'Lava',
    Potion: 'Potion',
    PowderSnow: 'PowderSnow',
    Water: 'Water',
} as const;

export const GameMode = {
    Adventure: 'Adventure',
    Creative: 'Creative',
    Spectator: 'Spectator',
    Survival: 'Survival',
} as const;

export const GameRule = {
    CommandBlockOutput: 'commandBlockOutput',
    CommandBlocksEnabled: 'commandBlocksEnabled',
    DoDayLightCycle: 'doDayLightCycle',
    DoEntityDrops: 'doEntityDrops',
    DoFireTick: 'doFireTick',
    DoImmediateRespawn: 'doImmediateRespawn',
    DoInsomnia: 'doInsomnia',
    DoLimitedCrafting: 'doLimitedCrafting',
    DoMobLoot: 'doMobLoot',
    DoMobSpawning: 'doMobSpawning',
    DoTileDrops: 'doTileDrops',
    DoWeatherCycle: 'doWeatherCycle',
    DrowningDamage: 'drowningDamage',
    FallDamage: 'fallDamage',
    FireDamage: 'fireDamage',
    FreezeDamage: 'freezeDamage',
    FunctionCommandLimit: 'functionCommandLimit',
    KeepInventory: 'keepInventory',
    MaxCommandChainLength: 'maxCommandChainLength',
    MobGriefing: 'mobGriefing',
    NaturalRegeneration: 'naturalRegeneration',
    PlayersSleepingPercentage: 'playersSleepingPercentage',
    ProjectilesCanBreakBlocks: 'projectilesCanBreakBlocks',
    Pvp: 'pvp',
    RandomTickSpeed: 'randomTickSpeed',
    RecipesUnlock: 'recipesUnlock',
    RespawnBlocksExplode: 'respawnBlocksExplode',
    SendCommandFeedback: 'sendCommandFeedback',
    ShowBorderEffect: 'showBorderEffect',
    ShowCoordinates: 'showCoordinates',
    ShowDaysPlayed: 'showDaysPlayed',
    ShowDeathMessages: 'showDeathMessages',
    ShowRecipeMessages: 'showRecipeMessages',
    ShowTags: 'showTags',
    SpawnRadius: 'spawnRadius',
    TntExplodes: 'tntExplodes',
    TntExplosionDropDecay: 'tntExplosionDropDecay',
} as const;

export const GraphicsMode = {
    Deferred: 'Deferred',
    Fancy: 'Fancy',
    RayTraced: 'RayTraced',
    Simple: 'Simple',
} as const;

export const HudElement = {
    PaperDoll: 0,
    Armor: 1,
    ToolTips: 2,
    TouchControls: 3,
    Crosshair: 4,
    Hotbar: 5,
    Health: 6,
    ProgressBar: 7,
    Hunger: 8,
    AirBubbles: 9,
    HorseHealth: 10,
    StatusEffects: 11,
    ItemText: 12,
} as const;

export const HudVisibility = {
    Hide: 0,
    Reset: 1,
} as const;

export const InputButton = {
    Jump: 'Jump',
    Sneak: 'Sneak',
} as const;

export const InputMode = {
    Gamepad: 'Gamepad',
    KeyboardAndMouse: 'KeyboardAndMouse',
    MotionController: 'MotionController',
    Touch: 'Touch',
} as const;

export const InputPermissionCategory = {
    Camera: 1,
    Movement: 2,
    LateralMovement: 4,
    Sneak: 5,
    Jump: 6,
    Mount: 7,
    Dismount: 8,
    MoveForward: 9,
    MoveBackward: 10,
    MoveLeft: 11,
    MoveRight: 12,
} as const;

export const ItemComponentTypes = {
    Compostable: 'minecraft:compostable',
    Cooldown: 'minecraft:cooldown',
    Durability: 'minecraft:durability',
    Enchantable: 'minecraft:enchantable',
    Food: 'minecraft:food',
} as const;

export const ItemLockMode = {
    inventory: 'inventory',
    none: 'none',
    slot: 'slot',
} as const;

export const LiquidType = {
    Water: 'Water',
} as const;

export const MemoryTier = {
    SuperLow: 0,
    Low: 1,
    Mid: 2,
    High: 3,
    SuperHigh: 4,
} as const;

export const MoonPhase = {
    FullMoon: 0,
    WaningGibbous: 1,
    FirstQuarter: 2,
    WaningCrescent: 3,
    NewMoon: 4,
    WaxingCrescent: 5,
    LastQuarter: 6,
    WaxingGibbous: 7,
} as const;

export const NamespaceNameErrorReason = {
    DisallowedNamespace: 'DisallowedNamespace',
    NoNamespace: 'NoNamespace',
} as const;

export const ObjectiveSortOrder = {
    Ascending: 0,
    Descending: 1,
} as const;

export const PaletteColor = {
    White: 0,
    Orange: 1,
    Magenta: 2,
    LightBlue: 3,
    Yellow: 4,
    Lime: 5,
    Pink: 6,
    Gray: 7,
    Silver: 8,
    Cyan: 9,
    Purple: 10,
    Blue: 11,
    Brown: 12,
    Green: 13,
    Red: 14,
    Black: 15,
} as const;

export const PlatformType = {
    Console: 'Console',
    Desktop: 'Desktop',
    Mobile: 'Mobile',
} as const;

export const ScoreboardIdentityType = {
    Entity: 'Entity',
    FakePlayer: 'FakePlayer',
    Player: 'Player',
} as const;

export const ScriptEventSource = {
    Block: 'Block',
    Entity: 'Entity',
    NPCDialogue: 'NPCDialogue',
    Server: 'Server',
} as const;

export const SignSide = {
    Back: 'Back',
    Front: 'Front',
} as const;

export const StructureAnimationMode = {
    Blocks: 'Blocks',
    Layers: 'Layers',
    None: 'None',
} as const;

export const StructureMirrorAxis = {
    None: 'None',
    X: 'X',
    XZ: 'XZ',
    Z: 'Z',
} as const;

export const StructureRotation = {
    None: 'None',
    Rotate180: 'Rotate180',
    Rotate270: 'Rotate270',
    Rotate90: 'Rotate90',
} as const;

export const StructureSaveMode = {
    Memory: 'Memory',
    World: 'World',
} as const;

export const TimeOfDay = {
    Day: 1000,
    Noon: 6000,
    Sunset: 12000,
    Night: 13000,
    Midnight: 18000,
    Sunrise: 23000,
} as const;

export const TintMethod = {
    BirchFoliage: 'BirchFoliage',
    DefaultFoliage: 'DefaultFoliage',
    DryFoliage: 'DryFoliage',
    EvergreenFoliage: 'EvergreenFoliage',
    Grass: 'Grass',
    None: 'None',
    Water: 'Water',
} as const;

export const WeatherType = {
    Clear: 'Clear',
    Rain: 'Rain',
    Thunder: 'Thunder',
} as const;

